export const GET_ISSUE_LOADING = 'GET_ISSUE_LOADING';
export const GET_ISSUE_SUCCESS = 'GET_ISSUE_SUCCESS';
export const GET_ISSUE_ERROR = 'GET_ISSUE_ERROR';

export const GET_ISSUES_LOADING = 'GET_ISSUES_LOADING';
export const GET_ISSUES_INITIAL_SUCCESS = 'GET_ISSUES_INITIAL_SUCCESS';
export const GET_ISSUES_NEXT_PAGE_SUCCESS = 'GET_ISSUES_NEXT_PAGE_SUCCESS';
export const GET_ISSUES_ERROR = 'GET_ISSUES_ERROR';
export const CHECK_IS_END_PAGE = 'CHECK_IS_END_PAGE';
